[package]
name = "scxmatch"
version = "0.1.0"

[workspace]
preview = ["pixi-build"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[package.host-dependencies]
hatchling = "*"
python = "3.9.*"

[dependencies]
python = "3.9.*"
scxmatch = { path = "." }
