name: Test MWE with Python 3.9-3.13

on:
  push:
    paths:
      - 'scxmatch/**'
      - 'tests/**'


jobs:
  test-bioconda-install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          channels: conda-forge, bioconda
          auto-activate-base: true

      - name: Install scxmatch and run test
        shell: bash -l {0}
        run: |
          conda create -n test-environment -y python=${{ matrix.python-version }} scxmatch==0.0.3
          conda activate test-environment
          python --version
          python tests/test_mwe.py
